version: '3'
services:
  mysql-8:
    image: 'mysql:8'
    ports:
      - '13306:3306'
    environment:
      MYSQL_DATABASE: lpji_local
      MYSQL_ROOT_PASSWORD: root
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

